baseurl = "https://spholmes.github.io/"
relativeurls = true
languageCode = "en-us"
title = "Susan Holmes: Archive"
theme = "hugo-tranquilpeak-theme"
googleAnalytics = "UA-92533297-1"
paginate = 7
canonifyurls = true
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", ".old$"]

[permalinks]
    post = "/:year/:month/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Susan Holmes"
  bio = "Statistician, Data Scientist, Mother, Grandmother, Advisor"
  job = "Professor of Statistics"
  location = "Stanford, CA, USA"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  # gravatarEmail = "susan@stat.stanford.edu"
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "https://res.cloudinary.com/sherlockph/image/upload/v1488056557/susan_lizad_qp3oet.png"
 twitter = "SherlockpHolmes"
  # Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
  # googlePlus = "+ThibaudLepretre"
  
[[menu.main]]
    weight = 0
    identifier ="home"
    name = "Homepage"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
    url = "http://statweb.stanford.edu/~susan/"

[[menu.links]]
  weight = 0
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/spholmes"
  
[[menu.links]]
   weight = 1
   identifier ="twitter"
   name = "Twitter"
   pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
    url = "https://twitter.com/SherlockpHolmes"

[[menu.links]]
   weight = 3
   identifier ="papers"
   name = "Papers"
   pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
    url = "http://statweb.stanford.edu/~susan/papers.html"

[[menu.links]]
  weight = 4
  identifier = "about"
  name = "Lab"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-users\"></i>"
  url = "http://statweb.stanford.edu/~susan/lab_index.html"




[params]
    description = "Resources, talks, videos."
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    clearReading = true
    dateFormat = "2017-02-25"
    hierarchicalCategories = true
    sidebarBehavior = 1
    keywords = ["Reproducible Research", "Data Science", "phylogenetics", "R"]
    coverImage = "http://res.cloudinary.com/sherlockph/image/upload/v1488056599/brighton-commute-starlings_hbhyu2.jpg"
    autoThumbnailImage = true
    thumbnailImage = true
    thumbnailImagePosition = "right"
    
[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

